apiVersion: v1
kind: Service
metadata:
  name: minio-s3
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "minio-s3"
  replicas: 3
  selector:
    matchLabels:
      app: minio-store
  template:
    metadata:
      labels:
        app: minio-store
    spec:
      containers:
      - name: minio
        image: minio/minio
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
