apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio

---

kind: Service
apiVersion: v1
metadata:
  name: minio-svc
  labels:
    app: minio
spec:
  selector:
    app: minio
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 9000

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  labels:
    app: minio
spec:
  serviceName: "minio-svc"
  replicas: 3                   # Creates 3 MinIO servers
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio
        volumeMounts:
        - name: minio-data
          mountPath: /data1
        args: ["server", "/data1"]
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
  volumeClaimTemplates: # This is the specification in which you reference the StorageClass
  - metadata:
      name: minio-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi        
      storageClassName: "minio-gp2" # This field references the existing StorageClass
